#!/usr/bin/env bash
# CustomPiOS OpenOCD module
# Written by Clemens Elflein
# GPL V3
########

# Source error handling, leave this in place
set -ex

source /common.sh
install_cleanup_trap

echo "Installing OpenOCD dependencys"
apt-get update --allow-releaseinfo-change
apt-get install --yes --no-install-recommends git autoconf automake build-essential pkg-config texinfo libtool libftdi-dev libusb-1.0-0-dev rpi.gpio-common

echo "Installing OpenOCD rp2040-v0.12.0"
git clone https://github.com/raspberrypi/openocd.git --recursive --branch rp2040-v0.12.0 --depth=1
cd openocd
./bootstrap
./configure --enable-ftdi --enable-sysfsgpio --enable-bcm2835gpio --disable-werror
make -j$(nproc)
make install
cd ..
rm -rf openocd

# Verify OpenOCD installation
echo "Verifying OpenOCD installation..."
openocd --version || echo "Warning: OpenOCD installation verification failed"



#cleanup
apt-get clean
apt-get autoremove --yes
