#!/usr/bin/env bash
# Preinstall customized config.txt
# Written by Stephan Wendel <me@stephanwe.de> aka KwadFan
# This file may distributed under GPLv3
# Copyright 2021
########

# Source error handling, leave this in place
set -ex

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

export BASE_ENABLE_UART=no

echo_green "Backup original config.txt and cmdline.txt ..."
mv "${PICONFIG_CONFIG_TXT_FILE}" "${PICONFIG_CONFIG_BAK_FILE}"
cp "${PICONFIG_CMDLINE_TXT_FILE}" "${PICONFIG_CMDLINE_BAK_FILE}"

echo_green "Copying files to root filesystem ..."
unpack /filesystem/root /

### Disable Console and services to enable Hardware Serial.
echo_green "Disable Serial Linux console ..."
sed -i 's/console=serial0,115200 //' "${PICONFIG_CMDLINE_TXT_FILE}"

### disable bluetooth and related services
echo_green "Disabling Bluetooth related services..."
systemctl_if_exists disable hciuart.service
systemctl_if_exists disable bluetooth.service
systemctl_if_exists disable bluealsa.service

### Configure locale
echo_green "Configuring locale to en_US.UTF-8..."
# Ensure en_US.UTF-8 is available and set as default
if [ -f /etc/locale.gen ]; then
    # Uncomment en_US.UTF-8 if it's commented out
    sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen || true
    # Generate locales
    locale-gen en_US.UTF-8 || echo "Warning: Could not generate en_US.UTF-8 locale"
    # Set as default
    echo "LANG=en_US.UTF-8" > /etc/default/locale
    echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 || echo "Warning: Could not update locale"
fi
